title: "Ramesh Pydi"
subtitle: "AI, Data & Microsoft Fabric"

name: "Ramesh Pydi"
description: "Sharing practical insights on Microsoft Fabric, AI, Power BI, and Data Engineering."

url: "https://rameshpydi.github.io"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

author:
  name: "Ramesh Pydi"

minimal_mistakes_skin: "default"

search: true
